//go:build !release_notices

package main

const thirdPartyNotices = "Atryum third-party notices were not embedded in this development build.\n\n" +
	"Release builds generated by `just build-prod` or `just release-build <tag>` embed the\n" +
	"full third-party notices bundle. Docker images also include the bundle under\n" +
	"/usr/share/doc/atryum.\n"
