package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: embed_notices <notices-dir> <output-go-file>")
		os.Exit(2)
	}

	noticesDir := os.Args[1]
	outputPath := os.Args[2]

	var files []string
	if err := filepath.WalkDir(noticesDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		files = append(files, path)
		return nil
	}); err != nil {
		fmt.Fprintf(os.Stderr, "walk notices: %v\n", err)
		os.Exit(1)
	}
	sort.Strings(files)

	var bundle bytes.Buffer
	bundle.WriteString("Atryum Third-Party Notices Bundle\n")
	bundle.WriteString("=================================\n\n")

	for _, file := range files {
		rel, err := filepath.Rel(noticesDir, file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "relative path: %v\n", err)
			os.Exit(1)
		}
		content, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", file, err)
			os.Exit(1)
		}
		bundle.WriteString("----- BEGIN ")
		bundle.WriteString(filepath.ToSlash(rel))
		bundle.WriteString(" -----\n")
		bundle.Write(content)
		if len(content) == 0 || content[len(content)-1] != '\n' {
			bundle.WriteByte('\n')
		}
		bundle.WriteString("----- END ")
		bundle.WriteString(filepath.ToSlash(rel))
		bundle.WriteString(" -----\n\n")
	}

	source := "// Code generated by scripts/embed_notices.go; DO NOT EDIT.\n" +
		"//go:build release_notices\n\n" +
		"package main\n\n" +
		"const thirdPartyNotices = " + strconv.Quote(bundle.String()) + "\n"

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output dir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, []byte(source), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outputPath, err)
		os.Exit(1)
	}
}
